#!/usr/bin/python3
"""
Project py-odf-report
© 2017 Georges Khaznadar <georgesk@debian.org>
This project aims to make it easy to generate reports or multiple
documents from one ODF template and values coming from a database.
Values can be numbers, strings, dates, images.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
import odfReport, os.path, sys
from odf import text, draw

if __name__=="__main__":
    thisdir=os.path.dirname(__file__)
    if len(sys.argv)>1:
        templatePath=sys.argv[1]
    else:
        templatePath=os.path.join(thisdir,"examples/sample1.odt")
    if len(sys.argv)>2:
        dataPath=sys.argv[2]
    else:
        dataPath=os.path.join(thisdir,"examples/data.csv")
    
    reporter=odfReport.Reporter(templatePath, dataPath)
    print ("Saved files:", reporter.run())
    
